[tool.black]
# Default line length
line-length = 100
target-version = ["py37"]

[tool.isort]
line_length = 100
indent = 4
multi_line_output = 3
default_section = "THIRDPARTY"
use_parentheses = true
combine_star = true
balanced_wrapping = false
known_tests = ["tests"]
combine_as_imports = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER", "TESTS"]
include_trailing_comma = true
